[tool.poetry]
name = "transformer"
version = "0.1.0"
description = ""
authors = ["Timon"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"